version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.2.0'
    working_directory: ~/countriesNowAPI
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: Update npm
      #     command: sudo npm i npm@latest -g
      - run:
          name: 'Install packages'
          command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'Run NYC Report'
          command: npm run report
      - run:
          name: Run Tests
          command: npm run test
      # - run: # run code coverage report
      #     name: code-coverage
      #     command: npm run coveralls
      # - coveralls/upload
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
